# load packages
using StatsPlots
using Plots
using Plots.Measures

#############################
# Plotting for single cells #
#############################
function plot_fit_single(t_data, c1_data, c1_fit, dosetimes, labels, filename)
    fig = plot(layout=(1,1),size=(400,300),grid=false,bottom_margin=3mm,left_margin=3mm,right_margin=3mm,top_margin=2mm)
    if labels == "None"
        plot!(t_data,c1_data,lw=2.5,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(15)),label="",subplot=1)
    else
        plot!(t_data,c1_data,lw=2.5,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=:bottomright, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(15)),label=labels,subplot=1,foreground_color_legend = nothing, background_color_legend=nothing, legendfontsize=11)
    end
    plot!(t_data,c1_fit,lw=2.5,ls=:dash,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)", color="black", labelfont = "Helvetica",label="",axis=(font(15)),subplot=1,ylims=(1.2,2.7))
    vline!(dosetimes,ls=:dot,linewidth=2.5,color="red",subplot=1,label="")
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_single(n_params, pj_collect, pl_collect, mle, filename) # model without kout
    df = n_params + 1
    threshold = mle .+ quantile(Chisq(df),0.95)
    fig = plot(layout=(1,5),size=(1800,300),grid=false,bottom_margin=20mm,left_margin=2mm,right_margin=5mm,top_margin=2mm)
    plot!(exp.(transpose(pj_collect[:,1,:])),transpose(pl_collect[:,1,:]),subplot=1,lw=3,xlabel="kin (1/s)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,2,:])),transpose(pl_collect[:,2,:]),subplot=2,lw=3,xlabel="kmet (1/s)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,3,:])),transpose(pl_collect[:,3,:]),subplot=3,lw=3,xlabel="Kd (uM)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,4,:])),transpose(pl_collect[:,4,:]),subplot=4,lw=3,xlabel="DAG (uM)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,5,:])),transpose(pl_collect[:,5,:]),subplot=5,lw=3,xlabel="sd (uM)",ylabel="",legend=:topright, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!(dag,ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    vline!(sd,ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_single_kout(n_params, pj_collect, pl_collect, mle, filename)  # model with kout
    df = n_params + 1
    threshold = mle .+ quantile(Chisq(df),0.95)
    fig = plot(layout=(2,3),size=(1000,550),grid=false,bottom_margin=10mm,left_margin=2mm,right_margin=5mm,top_margin=2mm)
    plot!(exp.(transpose(pj_collect[:,1,:])),transpose(pl_collect[:,1,:]),subplot=1,lw=3,xlabel="kin (1/s)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,2,:])),transpose(pl_collect[:,2,:]),subplot=2,lw=3,xlabel="kout (1/s)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,3,:])),transpose(pl_collect[:,3,:]),subplot=3,lw=3,xlabel="kmet (1/s)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,4,:])),transpose(pl_collect[:,4,:]),subplot=4,lw=3,xlabel="Kd (uM)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,5,:])),transpose(pl_collect[:,5,:]),subplot=5,lw=3,xlabel="DAG (uM)",ylabel="",legend=false, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,6,:])),transpose(pl_collect[:,6,:]),subplot=6,lw=3,xlabel="sd (uM)",ylabel="",legend=:topright, palette=palette(:rainbow), labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kout],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    vline!(dag,ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    vline!(sd,ls=:dot,linewidth=3,color="blue",subplot=6,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=6,label="")
    display(fig)
    savefig(fig,filename)
end

###############################
# Plotting for multiple cells #
###############################
function plot_fit(cells_to_plot, t_data, c1_data, c1_fit, dosetimes, labels, filename)
    fig = plot(layout=(1,1),size=(400,300),grid=false,bottom_margin=3mm,left_margin=3mm,right_margin=3mm,top_margin=2mm,framestyle = :box)
    plot!(t_data,c1_data,lw=1,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=false, color="grey85", labelfont = "Helvetica",axis=(font(15)),label="",subplot=1)
    if labels == "None"
        plot!(t_data[:,1:cells_to_plot],c1_data[:,1:cells_to_plot],lw=1.5,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=false, color="yellowgreen", labelfont = "Helvetica",axis=(font(15)),label="",subplot=1)
    else
        plot!(t_data[:,1:cells_to_plot],c1_data[:,1:cells_to_plot],lw=1.5,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=:bottomright,  color="yellowgreen", labelfont = "Helvetica",axis=(font(15)),label=labels,foreground_color_legend = nothing, background_color_legend=nothing, legendfontsize=11,subplot=1)
    end
    plot!(t_data[:,1:cells_to_plot],c1_fit[:,1:cells_to_plot],lw=1.5,ls=:dash,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)", color="black", labelfont = "Helvetica",label="",axis=(font(15)),subplot=1)
    vline!(dosetimes,ls=:dot,linewidth=2,color="red",subplot=1,label="")
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_sim_dag(cells, n_params, pj, pl, pj_dag, pl_dag, mle, mle_params, mle_dag, filename, kin,kmet,Kd,sd,dag)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(2,3),size=(1200,600),grid=false,bottom_margin=10mm,left_margin=8mm,right_margin=3mm,top_margin=2mm,framestyle = :box)
    plot!(exp.(pj[1,:]),pl[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[2,:]),pl[2,:],subplot=2,lw=2,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[3,:]),pl[3,:],subplot=3,lw=2,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[4,:]),pl[4,:],subplot=4,lw=2,xlabel="sd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(pj_dag[1,:],pl_dag[1,:],lw=2,subplot=5,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[2,:],pl_dag[2,:],lw=2,subplot=5,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[3,:],pl_dag[3,:],lw=2,subplot=5,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[4,:],pl_dag[4,:],lw=2,subplot=5,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[5,:],pl_dag[5,:],lw=2,subplot=5,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(legend=false,grid=false,foreground_color_subplot=:white,xaxis=false,yaxis=false,subplot=6)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!([sd[1]],ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    vline!(dag[1:5],ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=4,color="red",ms=6,label="",msw=0)
    scatter!(mle_dag,repeat([mle],5),subplot=5,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_sim_dag_kout(cells, n_params, pj, pl, pj_dag, pl_dag, mle, mle_params, mle_dag, filename, kin,kmet,Kd,sd,dag)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(2,3),size=(1200,600),grid=false,bottom_margin=10mm,left_margin=8mm,right_margin=3mm,top_margin=2mm,framestyle = :box)
    plot!(exp.(pj[1,:]),pl[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[2,:]),pl[2,:],subplot=2,lw=2,xlabel="kout (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[3,:]),pl[3,:],subplot=3,lw=2,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[4,:]),pl[4,:],subplot=4,lw=2,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[5,:]),pl[5,:],subplot=5,lw=2,xlabel="sd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(pj_dag[1,:],pl_dag[1,:],lw=2,subplot=6,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[2,:],pl_dag[2,:],lw=2,subplot=6,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[3,:],pl_dag[3,:],lw=2,subplot=6,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[4,:],pl_dag[4,:],lw=2,subplot=6,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[5,:],pl_dag[5,:],lw=2,subplot=6,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kout],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    vline!([sd[1]],ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    vline!(dag[1:5],ls=:dot,linewidth=3,color="blue",subplot=6,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=6,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=4,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[5]],[mle],subplot=5,color="red",ms=6,label="",msw=0)
    scatter!(mle_dag,repeat([mle],5),subplot=6,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_sim_dag_align(cells, n_params, pj, pl, pj_dag, pl_dag, mle, mle_params, mle_dag, filename, kin,kmet,Kd,sd,dag)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(1,5),size=(1800,300),grid=false,bottom_margin=20mm,left_margin=5mm,right_margin=2mm,top_margin=2mm)
    plot!(exp.(pj[1,:]),pl[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[2,:]),pl[2,:],subplot=2,lw=2,xlabel="kmet (1/s)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[3,:]),pl[3,:],subplot=3,lw=2,xlabel="Kd (uM)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[4,:]),pl[4,:],subplot=5,lw=2,xlabel="sd (uM)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(pj_dag[1,:],pl_dag[1,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[2,:],pl_dag[2,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[3,:],pl_dag[3,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[4,:],pl_dag[4,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[5,:],pl_dag[5,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!([sd[1]],ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    vline!(dag[1:5],ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=5,color="red",ms=6,label="",msw=0)
    scatter!(mle_dag,repeat([mle],5),subplot=4,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_expt_dag(cells, n_params, pj, pl, pj_dag, pl_dag, mle, mle_params, mle_dag, filename)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(2,3),size=(1200,600),grid=false,bottom_margin=10mm,left_margin=8mm,right_margin=3mm,top_margin=2mm,framestyle = :box)
    plot!(exp.(pj[1,:]),pl[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[2,:]),pl[2,:],subplot=2,lw=2,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[3,:]),pl[3,:],subplot=3,lw=2,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[4,:]),pl[4,:],subplot=5,lw=2,xlabel="sd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(pj_dag[1,:],pl_dag[1,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[2,:],pl_dag[2,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[3,:],pl_dag[3,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[4,:],pl_dag[4,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[5,:],pl_dag[5,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(legend=false,grid=false,foreground_color_subplot=:white,xaxis=false,yaxis=false,subplot=6)
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=5,color="red",ms=6,label="",msw=0)
    scatter!(mle_dag,repeat([mle],5),subplot=4,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_expt_dag_align(cells, n_params, pj, pl, pj_dag, pl_dag, mle, mle_params, mle_dag, filename)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(1,5),size=(1800,350),grid=false,bottom_margin=20mm,left_margin=3mm,right_margin=2mm,top_margin=2mm,framestyle = :box)
    plot!(exp.(pj[1,:]),pl[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[2,:]),pl[2,:],subplot=2,lw=2,xlabel="kmet (1/s)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[3,:]),pl[3,:],subplot=3,lw=2,xlabel="Kd (uM)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(exp.(pj[4,:]),pl[4,:],subplot=5,lw=2,xlabel="sd (uM)",ylabel="",legend=false, color="black", labelfont = "Helvetica",axis=(font(18)),label="",xaxis=:log)
    plot!(pj_dag[1,:],pl_dag[1,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[2,:],pl_dag[2,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[3,:],pl_dag[3,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[4,:],pl_dag[4,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(pj_dag[5,:],pl_dag[5,:],lw=2,subplot=4,color="black",label="",xlabel="DAG (uM)",ylabel="",labelfont = "Helvetica",axis=(font(18)),xaxis=:log)
    plot!(legend=false,grid=false,foreground_color_subplot=:white,xaxis=false,yaxis=false,subplot=6)
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=5,color="red",ms=6,label="",msw=0)
    scatter!(mle_dag,repeat([mle],5),subplot=4,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles(cells, n_params, pj_collect, pl_collect, mle, mle_params, filename)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(2,2),size=(800,500),grid=false,bottom_margin=5mm,left_margin=10mm,right_margin=3mm,top_margin=2mm)
    plot!(exp.(pj_collect[1,:]),pl_collect[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[2,:]),pl_collect[2,:],subplot=2,lw=2,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[3,:]),pl_collect[3,:],subplot=3,lw=2,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[4,:]),pl_collect[4,:],subplot=4,lw=2,xlabel="sd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=4,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_profiles_kout(cells, n_params, pj_collect, pl_collect, mle, mle_params, filename)
    df = n_params + cells
    threshold = mle + quantile(Chisq(df),0.95)
    fig = plot(layout=(2,3),size=(1000,500),grid=false,bottom_margin=5mm,left_margin=10mm,right_margin=3mm,top_margin=2mm)
    plot!(exp.(pj_collect[1,:]),pl_collect[1,:],subplot=1,lw=2,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[2,:]),pl_collect[2,:],subplot=2,lw=2,xlabel="kout (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[3,:]),pl_collect[3,:],subplot=3,lw=2,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[4,:]),pl_collect[4,:],subplot=4,lw=2,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(exp.(pj_collect[5,:]),pl_collect[5,:],subplot=5,lw=2,xlabel="sd (uM)",ylabel="-log(Likelihood)",legend=false, color="black", labelfont = "Helvetica",axis=(font(15)),label="",xaxis=:log)
    plot!(legend=false,grid=false,foreground_color_subplot=:white,xaxis=false,yaxis=false,subplot=6)
    vline!([kin],ls=:dot,linewidth=3,color="blue",subplot=1,label="")
    vline!([kout],ls=:dot,linewidth=3,color="blue",subplot=2,label="")
    vline!([kmet],ls=:dot,linewidth=3,color="blue",subplot=3,label="")
    vline!([Kd],ls=:dot,linewidth=3,color="blue",subplot=4,label="")
    vline!([sd[1]],ls=:dot,linewidth=3,color="blue",subplot=5,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=3,color="grey",subplot=1,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=3,color="grey",subplot=2,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=3,color="grey",subplot=3,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=3,color="grey",subplot=4,label="")
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=3,color="grey",subplot=5,label="")
    scatter!([mle_params[1]],[mle],subplot=1,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[2]],[mle],subplot=2,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[3]],[mle],subplot=3,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[4]],[mle],subplot=4,color="red",ms=6,label="",msw=0)
    scatter!([mle_params[5]],[mle],subplot=5,color="red",ms=6,label="",msw=0)
    display(fig)
    savefig(fig,filename)
end

function plot_DAGprofiles(cells,n_params,pl_collect,pj_collect,mle, mle_params, filename)
    threshold = mle + quantile(Chisq(n_params + cells),0.95)
    fig = plot(layout=(1,1),size=(500,300),grid=false,framestyle = :box, bottom_margin=5mm,left_margin=5mm,right_margin=3mm,top_margin=5mm)
    plot!(pj_collect[1,:],pl_collect[1,:],lw=2,subplot=1,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)))
    plot!(pj_collect[2,:],pl_collect[2,:],lw=2,subplot=1,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)))
    plot!(pj_collect[3,:],pl_collect[3,:],lw=2,subplot=1,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)))
    plot!(pj_collect[4,:],pl_collect[4,:],lw=2,subplot=1,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)))
    plot!(pj_collect[5,:],pl_collect[5,:],lw=2,subplot=1,color="black",label="",xlabel="DAG (uM)",ylabel="-log(Likelihood)",labelfont = "Helvetica",axis=(font(18)))
    scatter!(mle_params,repeat([mle],5),color="red",ms=6,label="",msw=0)
    plot!([threshold], seriestype="hline",ls=:dash,linewidth=2,color="grey",label="")
    display(fig)
    savefig(fig,filename)
end

function pairplot_sim(dag,c1_recruit,r_params,dag_err1,dag_err2,dag_bins,c1_bins,dag_lims,c1_lims,filename,cells)
    l = layout = @layout [a _
                          b{0.8w,0.7h} c]
    p1 = scatter(r_params[end,:], c1_recruit[1:cells], ms=5, ylabel="C1 recruitment (uM)",xlabel="Uncaged DAG (uM)",legend=false, color="grey80", msc="grey80",labelfont = "Helvetica",axis=(font(15)),label="Fit",framestyle = :box)
    p1 = scatter!(dag[1:cells],c1_recruit[1:cells],ms=5,ylabel="C1 recruitment (uM)",xlabel="Uncaged DAG (uM)",legend=false, color="skyblue", msc="skyblue",labelfont = "Helvetica",axis=(font(15)),label="True",foreground_color_legend = nothing, background_color_legend=nothing, legendfontsize=10,xlim=dag_lims,ylim=c1_lims)
    p1 = vline!([mean(dag[1:cells])],linewidth=1,color="black",label="")
    p1 = vline!([mean(dag[1:cells])-std(dag[1:cells])],ls=:dash,linewidth=1,color="black",label="")
    p1 = vline!([std(dag[1:cells])+mean(dag[1:cells])],ls=:dash,linewidth=1,color="black",label="")
    p1 = scatter!(r_params[end,1:5],c1_recruit[1:5],xerr = (dag_err1,dag_err2), color="grey60",ms=5)
    p1 = scatter!(dag[1:5],c1_recruit[1:5], color="blue",ms=5)
    p3 = histogram(c1_recruit[1:cells], orientation = :h, framestyle = :none,lw=1,color="grey60",lc=:match,legend=false,bins=c1_bins,ylims=c1_lims)
    p2 = histogram(dag[1:cells], orientation = :v, framestyle = :none,lw=1,color="blue",lc=:match,label="True",foreground_color_legend = nothing, background_color_legend=nothing, legendfontsize=11,bins=dag_bins,xlims=dag_lims)
    p2 = histogram!(r_params[end,:], orientation = :v, framestyle = :none,lw=1,color="grey60",lc=:match,label="Fit",bins=dag_bins,xlims=dag_lims)
    p2 = vline!([mean(dag[1:cells])],linewidth=1,color="black",label="")
    p2 = vline!([mean(dag[1:cells])-std(dag[1:cells])],ls=:dash,linewidth=1,color="black",label="")
    p2 = vline!([std(dag[1:cells])+mean(dag[1:cells])],ls=:dash,linewidth=1,color="black",label="")
    fig = plot(p2,p1,p3,layout = l,size=(500,400),grid=false,top_margin=0mm,bottom_margin=0mm,right_margin=0mm)
    display(fig)
    savefig(filename)
end

function pairplot_expt(c1_recruit,r_params,dag_err1,dag_err2,dag_bins,c1_bins,dag_lims,c1_lims,dag_mean,dag_sd,filename,cells)
    l = layout = @layout [a _
                  b{0.8w,0.7h} c]
    p1 = scatter(r_params[end,:], c1_recruit[1:cells], ms=5, ylabel="C1 recruitment (uM)",xlabel="Uncaged DAG (uM)",legend=false, color="grey80", msc="grey80",labelfont = "Helvetica",axis=(font(15)),label="Fit",framestyle = :box,xlims=dag_lims,ylims=c1_lims)
    p1 = vline!([dag_mean],linewidth=1,color="black",label="")
    p1 = vline!([dag_mean-dag_sd],ls=:dash,linewidth=1,color="black",label="")
    p1 = vline!([dag_mean+dag_sd],ls=:dash,linewidth=1,color="black",label="")
    p1 = scatter!(r_params[end,1:5],c1_recruit[1:5],xerr = (dag_err1,dag_err2), color="black",ms=5)
    p3 = histogram(c1_recruit[1:cells], orientation = :h, framestyle = :none,lw=1,color="grey60",lc=:match,legend=false,bins=c1_bins,ylims=c1_lims)
    p2 = histogram(r_params[end,:], orientation = :v, framestyle = :none,lw=1,color="grey60",lc=:match,label="Fit",legend=false,bins=dag_bins,xlims=dag_lims)
    p2 = vline!([dag_mean],linewidth=1,color="black",label="")
    p2 = vline!([dag_mean-dag_sd],ls=:dash,linewidth=1,color="black",label="")
    p2 = vline!([dag_mean+dag_sd],ls=:dash,linewidth=1,color="black",label="")
    fig = plot(p2,p1,p3,layout = l,size=(500,400),grid=false,top_margin=0mm,bottom_margin=0mm,right_margin=0mm)
    display(fig)
    savefig(filename)
end

################################################
# Plotting for fitting on population mean data #
################################################

function plot_profiles_single_mean(cells, n_profiles, n_params, pj_collect, pl_collect, mle, labels, filename)
    df = n_params
    # threshold = mle .+ quantile(Chisq(df),0.95)
    threshold = (minimum(pl_collect,dims=(2,3)) .+ quantile(Chisq(df),0.95))[:,1]
    fig = plot(layout=(2,2),size=(700,500),grid=false,bottom_margin=5mm,left_margin=2mm,right_margin=5mm,top_margin=2mm,framestyle=:box)
    plot!(exp.(transpose(pj_collect[:,1,:])),transpose(pl_collect[:,1,:]),subplot=1,lw=3,xlabel="kin (1/s)",ylabel="-log(Likelihood)",legend=false, palette=:rainbow, labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,2,:])),transpose(pl_collect[:,2,:]),subplot=2,lw=3,xlabel="kmet (1/s)",ylabel="-log(Likelihood)",legend=false, palette=:rainbow, labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,3,:])),transpose(pl_collect[:,3,:]),subplot=3,lw=3,xlabel="Kd (uM)",ylabel="-log(Likelihood)",legend=false, palette=:rainbow, labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(exp.(transpose(pj_collect[:,4,:])),transpose(pl_collect[:,4,:]),subplot=4,lw=3,xlabel="DAG (uM)",ylabel="-log(Likelihood)",legend=false, palette=:rainbow, labelfont = "Helvetica",axis=(font(17)),label="",xaxis=:log)
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=1,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=2,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=3,label="")
    plot!(threshold, seriestype="hline",ls=:dash,linewidth=2,color="grey",subplot=4,label="")
    display(fig)
    savefig(fig,filename)
end

function plot_fit_single_mean(cells, t_data, c1_data, c1_fit, dosetimes, labels, filename)
    fig = plot(layout=(1,1),size=(400,250),grid=false,bottom_margin=3mm,left_margin=3mm,right_margin=3mm,top_margin=2mm, framestyle = :box)
    if labels == "None"
        plot!(t_data,c1_data,lw=3,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=false, palette=:rainbow, labelfont = "Helvetica",axis=(font(15)),label="",subplot=1)
    else
        plot!(t_data,c1_data,lw=3,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)",legend=:outertopright, palette=:rainbow, labelfont = "Helvetica",axis=(font(15)),label=labels,subplot=1,foreground_color_legend = nothing, background_color_legend=nothing, legendfontsize=11)
    end
    plot!(t_data,c1_fit,lw=1.5,ls=:dash,xlabel="Time (s)",ylabel="C1-EGFP-NES (uM)", color="black", labelfont = "Helvetica",label="",axis=(font(15)),subplot=1,ylim=(3.2,5.5))
    vline!(dosetimes,ls=:dot,linewidth=2.5,color="red",subplot=1,label="")
    display(fig)
    savefig(fig,filename)
end